USE [master]
GO
/****** Object:  Database [StockMarketDB]    Script Date: 4/10/2019 5:19:29 PM ******/
CREATE DATABASE [StockMarketDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StockMarketDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\StockMarketDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StockMarketDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\StockMarketDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [StockMarketDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockMarketDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [StockMarketDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [StockMarketDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [StockMarketDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [StockMarketDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [StockMarketDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [StockMarketDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [StockMarketDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [StockMarketDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [StockMarketDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [StockMarketDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [StockMarketDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [StockMarketDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [StockMarketDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [StockMarketDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [StockMarketDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [StockMarketDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [StockMarketDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [StockMarketDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [StockMarketDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [StockMarketDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [StockMarketDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [StockMarketDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [StockMarketDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [StockMarketDB] SET  MULTI_USER 
GO
ALTER DATABASE [StockMarketDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [StockMarketDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [StockMarketDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [StockMarketDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [StockMarketDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [StockMarketDB] SET QUERY_STORE = OFF
GO
USE [StockMarketDB]
GO
/****** Object:  Table [dbo].[Company]    Script Date: 4/10/2019 5:19:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Company](
	[Symbol] [varchar](50) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Sector] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED 
(
	[Symbol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Favorites]    Script Date: 4/10/2019 5:19:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Favorites](
	[Id] [int] NOT NULL,
	[Symbol] [varchar](10) NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_Favorites] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_Symbol] UNIQUE NONCLUSTERED 
(
	[Symbol] ASC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Portfolio]    Script Date: 4/10/2019 5:19:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Portfolio](
	[Id] [int] NOT NULL,
	[Symbol] [varchar](50) NOT NULL,
	[NumberOfShares] [int] NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_Portfolio] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transactions]    Script Date: 4/10/2019 5:19:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[Id] [int] NOT NULL,
	[Symbol] [varchar](50) NOT NULL,
	[NumberOfShares] [int] NOT NULL,
	[Price] [money] NOT NULL,
	[Date] [date] NOT NULL,
	[BuyOrSell] [varchar](4) NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 4/10/2019 5:19:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Hash] [varchar](50) NOT NULL,
	[Salt] [varchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Favorites]  WITH CHECK ADD  CONSTRAINT [FK_Favorites_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Favorites] CHECK CONSTRAINT [FK_Favorites_User]
GO
ALTER TABLE [dbo].[Portfolio]  WITH CHECK ADD  CONSTRAINT [FK__Portfolio__UserI__4E88ABD4] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Portfolio] CHECK CONSTRAINT [FK__Portfolio__UserI__4E88ABD4]
GO
ALTER TABLE [dbo].[Portfolio]  WITH CHECK ADD  CONSTRAINT [FK_Portfolio_Company] FOREIGN KEY([Symbol])
REFERENCES [dbo].[Company] ([Symbol])
GO
ALTER TABLE [dbo].[Portfolio] CHECK CONSTRAINT [FK_Portfolio_Company]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_User]
GO
USE [master]
GO
ALTER DATABASE [StockMarketDB] SET  READ_WRITE 
GO



USE StockMarketDB
Go

BULK INSERT Company
FROM 'C:\workspace\team\virtual-stock-market\StockerWebApi\Stocker\DAL\SQL\SP500List.csv'
WITH
(
    FORMAT = 'CSV', 
    FIELDQUOTE = '"',
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK
)

