USE [master]
GO

/****** Object:  Database [StockMarketDB]    Script Date: 4/8/2019 10:05:54 AM ******/
CREATE DATABASE [StockMarketDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StockMarketDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\StockMarketDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StockMarketDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\StockMarketDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [StockMarketDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockMarketDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StockMarketDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StockMarketDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StockMarketDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StockMarketDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StockMarketDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [StockMarketDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StockMarketDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StockMarketDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StockMarketDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StockMarketDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StockMarketDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StockMarketDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StockMarketDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StockMarketDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StockMarketDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StockMarketDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StockMarketDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StockMarketDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StockMarketDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StockMarketDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StockMarketDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StockMarketDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StockMarketDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StockMarketDB] SET  MULTI_USER 
GO

ALTER DATABASE [StockMarketDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StockMarketDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StockMarketDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StockMarketDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StockMarketDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StockMarketDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StockMarketDB] SET  READ_WRITE 
GO
